<?php

/**
 * @package pvcErr
 * @author: Doug Wilbourne (dougwilbourne@gmail.com)
 */

declare(strict_types=1);

namespace pvc\err\stock;

/**
 *
 * Bad method call exceptions should be thrown when you try to invoke a non-existent method on an object.
 *
 * The PHP library does not use this exception itself (it throws an error instead in the above circumstance),
 * so this exception can only be generated by throwing it explicitly in your code.
 *
 * Example:
 *
 *    class Foo {
 *        function __call($method_name, $args) {
 *            throw new pvc\BadMethodCallException($method_name);
 *        }
 *    }
 *
 *    $f = new Foo();
 *    $f->doSomethingCrazy();
 *
 * @package pvcErr
 */
class BadMethodCallException extends Exception
{
}
