<?php

/**
 * @package pvcErr
 * @author: Doug Wilbourne (dougwilbourne@gmail.com)
 */

declare(strict_types=1);

namespace pvc\err\stock;

/**
 *
 * Length exceptions should be thrown when a length is invalid.
 *
 * The PHP library does not use this exception itself, so this exception can only be generated by throwing it
 * explicitly in your code.
 *
 * Example:
 *
 *    function shortenArrayToLength(array $array, int $n) {
 *        if ($n < 0) {
 *            throw new LengthException("array length cannot be negative.");
 *        }
 *        else {
 *            while(count($array) > $n) {
 *                array_shift($array);
 *            }
 *        }
 *    }
 *
 * @package pvcErr
 */
class LengthException extends LogicException
{
}
