<?php declare(strict_types = 1);

namespace pvc\err\throwable\exception\stock_rebrands;

use pvc\err\throwable\ErrorExceptionConstants as ec;
use pvc\msg\ErrorExceptionMsg;
use Throwable;

/**
 *
 * Overflow exceptions should be thrown when you try "adding an element to a full container."
 *
 * The PHP library does not use this exception itself.  This exception can only be generated by throwing it
 * explicitly in your code.
 *
 */
class OverflowException extends RuntimeException
{
    public function __construct(ErrorExceptionMsg $msg, int $code, Throwable $previous)
    {
        if ($code == 0) {
            $code = ec::OVERFLOW_EXCEPTION;
        }
        parent::__construct($msg, $code, $previous);
    }
}
