<?php declare(strict_types = 1);

namespace pvc\err\stock\exceptions;

use pvc\err\stock\ExceptionConstants;
use pvc\msg\Msg;
use Throwable;

/**
 *
 * Length exceptions should be thrown when a length is invalid.
 *
 * The PHP library does not use this exception itself, so this exception can only be generated by throwing it
 * explicitly in your code.
 *
 * Example:
 *
 *    function shortenArrayToLength(array $array, int $n) {
 *        if ($n < 0) {
 *            throw new LengthException("array length cannot be negative.");
 *        }
 *        else {
 *            while(count($array) > $n) {
 *                array_shift($array);
 *            }
 *        }
 *    }
 *
 */
class LengthException extends LogicException
{
    public function __construct(Msg $msg, Throwable $previous = null)
    {
        parent::__construct($msg, $previous);
        $this->code = ExceptionConstants::LENGTH_EXCEPTION;
    }
}
