<?php declare(strict_types = 1);

namespace pvc\err\stock\exceptions;

use pvc\err\stock\ExceptionConstants;
use pvc\msg\Msg;
use Throwable;

/**
 *
 * Overflow exceptions should be thrown when you try "adding an element to a full container."
 *
 * The PHP library does not use this exception itself.  This exception can only be generated by throwing it
 * explicitly in your code.
 *
 */
class OverflowException extends RuntimeException
{
    public function __construct(Msg $msg, Throwable $previous)
    {
        parent::__construct($msg, $previous);
        $this->code = ExceptionConstants::OVERFLOW_EXCEPTION;
    }
}
